# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js
# Build a general Node.js project with npm.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'


# TAREAS AGREGADAS PARA PUBLICACIÓN DEL ARTEFACTO


# 1. Tarea para copiar los archivos compilados
- task: CopyFiles@2
  displayName: 'Copiar Archivos de Compilación a Staging'
  inputs:
    # Usamos 'dist/**' porque NestJS usa la carpeta 'dist' por defecto
    Contents: 'dist/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)' # Ruta temporal estándar de la Pipeline

# 2. Tarea para publicar el artefacto
- task: PublishBuildArtifacts@1
  displayName: 'Publicar Artefacto Versionado'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BancoMateriales' # Puedes darle el nombre que prefieras
    publishLocation: 'Container'